/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CtrlAgenda;
import controladores.CtrlUsuario;

/**
 *
 * @author Promethevs
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskFondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        opcSalir = new javax.swing.JMenuItem();
        mnuBasicos = new javax.swing.JMenu();
        opcPersonas = new javax.swing.JMenuItem();
        opcAgendaActionPerformed = new javax.swing.JMenuItem();
        mnuOperaciones = new javax.swing.JMenu();
        mnuReportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Propiedades G & G");
        setExtendedState(6);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout dskFondoLayout = new javax.swing.GroupLayout(dskFondo);
        dskFondo.setLayout(dskFondoLayout);
        dskFondoLayout.setHorizontalGroup(
            dskFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dskFondoLayout.setVerticalGroup(
            dskFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(dskFondo);

        mnuArchivo.setText("Archivo");

        opcSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_shutdown_32px.png"))); // NOI18N
        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(opcSalir);

        jMenuBar1.add(mnuArchivo);

        mnuBasicos.setText("Básicos");

        opcPersonas.setText("Usuarios");
        opcPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcPersonasActionPerformed(evt);
            }
        });
        mnuBasicos.add(opcPersonas);

        opcAgendaActionPerformed.setText("Agenda");
        opcAgendaActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAgendaActionPerformedActionPerformed(evt);
            }
        });
        mnuBasicos.add(opcAgendaActionPerformed);

        jMenuBar1.add(mnuBasicos);

        mnuOperaciones.setText("Operaciones");
        jMenuBar1.add(mnuOperaciones);

        mnuReportes.setText("Reportes");
        jMenuBar1.add(mnuReportes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcPersonasActionPerformed
        // TODO add your handling code here:
//        FrmPersonas p = new FrmPersonas();
//        p.setVisible( true );
//        this.dskFondo.add( p );
        new CtrlUsuario(FrmUsuarios.getInstancia()).iniciar();
    }//GEN-LAST:event_opcPersonasActionPerformed

    private void opcAgendaActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAgendaActionPerformedActionPerformed
        // TODO add your handling code here:
        new CtrlAgenda(FrmContactos.getInstancia()).iniciar();
    }//GEN-LAST:event_opcAgendaActionPerformedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dskFondo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuBasicos;
    private javax.swing.JMenu mnuOperaciones;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem opcAgendaActionPerformed;
    private javax.swing.JMenuItem opcPersonas;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}
